name: deploy
on:
  push:
    branches:
    - Challenge_6

  jobs:
    run_update:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
      - name: print out run update git and compile
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 203.194.113.54
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: |
            cd /home/apps/ach-fajarr/Synrgy6-AkhmadFajar
            git pull origin main
            mvn clean install
      - name: print out run update git and compile
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 203.194.113.54
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: |
            cd /home/apps/ach-fajarr/Synrgy6-AkhmadFajar
            kill $(cat ./pid.file)
            cp -f /home/apps/ach-fajarr/Synrgy6-AkhmadFajar/target/Synrgy6-AkhmadFajar-0.0.1-SNAPSHOT.jar
            ./start_silent
            
