server:
  port: 8081

spring:
  application:
    name: email

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include=*: